### ISSUE TITLE
The potential problem

### ISSUE THREAD

**Issue by anes66** [Randolio/randol_cargo#1]
The potential problem that I see here is that if the player gets disconnected or leaves the server, the vehicle and prop are not deleted but remain on the server. It would be great if you could implement, if the player exits the server or gets a crash, the vehicle with the prop will be deleted.

and also a suggestion if you can make a function so peopel nowdays use key system so that they can put export so you done with the basics

**Comment by Randolio** [comment]
I will add it tomorrow.

**Comment by Randolio** [comment]
Fixed.
