### ISSUE TITLE
Possible To Exit Vehicle When Dropping Off Cargo

### ISSUE THREAD

**Issue by yiruzu** [Randolio/randol_cargo#5]
It results in the vehicle still being frozen after getting back in.

**Comment by Randolio** [comment]
Why are you getting out whilst dropping off?

**Comment by yiruzu** [comment]
The first time was accidental, which can happen to anyone. Some players might not know what to do and leave. It's a bug that needs fixing, so it doesn't really matter why I think so.

**Comment by Randolio** [comment]
I wasn't able to reproduce the issue myself. Must be a server delay and a fat finger to achieve this. Removed freezing of the vehicle regardless.
